### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by AndreasSchantl** [kooohei/brackets-synapse#10]
I am not able to update to the newest version...

**Comment by kooohei** [comment]
ok what version your brackets?
if version higher than 1.3 

try below.

click "Show Extension Folder" on Help menu.
and then open the "user" folder then surely brackets-synapse folder is there.
that should be remove, and restart Brackets.
please reinstall Synapse from Extension Manager.

Your Synapse's configuration is not delete via above things.

**Comment by AndreasSchantl** [comment]
Okay, I have done that already before you have written that. I could reinstall it then without any problems and it is working now. But it seems to me that there is a problem with your code when it comes to updates.

**Comment by kooohei** [comment]
thank you for the reply
yea I know, there is problems in my code yet.
that code is dirty, because this extension made for learn to js, github and engish usage by me. 
(most necessary is my English skill..)

anyway, if there is problems for extension’s basically function.
please help for feed back.

thx.
