### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by PooLP** [kooohei/brackets-synapse#38]
Hi,

If server disconnect connexion, Synapse do not reconnect. We must restart Bracket for work again.

and, PLEASE, use Bracket console for error/log not a custom window and I have same remark for file browser, configuration ... use Bracket UI/UX, Take example on Grunt for Bracket and GIT for bracket.

Thanks

**Comment by kooohei** [comment]
ok i got it about connection problem. 
and the log, I was read the ui policy for brackets.  maybe you say Brackets console is the bottom panel   below of editor area, but I dont think this case, because b/p is too big and ugly only to show the log. most problem is that position is below the editor area. I think about this problem. anyway probably I will change the fix bottom position to other some methods.

**Comment by PooLP** [comment]
I think an extension developer should respect the ergonomics (UI / UX) of the application, even if he thinks it's ugly, it's more easy to maintenance ;)

apart this and the disconnection bug, your extension is very well !

**Comment by kooohei** [comment]
yes you right. and of course I respect to all contributors, 
I saw bottom panel is ugly, but I appended "only to show the log"
If the words were not cod, it is "by this extension"
this case is limiting too much.　please be aware it.

But what you said is I understand to be a very important as versatility.

thx,

**Comment by kooohei** [comment]
Console moved from 1.2.1

**Comment by PooLP** [comment]
Ok, I test this ;)
