### ISSUE TITLE
Alphabetical files sorting

### ISSUE THREAD

**Issue by magnetas** [kooohei/brackets-synapse#59]
I've seen a closed issue related to the way the files are listed but I don't think it was solved.

The extension itself is the best there is for working over FTP directly, brackets became my main editor once again.

However I have no idea what files sorting algorithm is used. I don't think they're sorted by create date and they're definitely not sorter by filename. Directories are listed before files and that's about it.

Is there a way to change that or at least do you have any thoughts on when it will be possible to sort files alphabetically?

Thank you.

**Comment by kooohei** [comment]
hi.
I'm wondering. I answered same question somewhere... I forgot.

there is plan already to the Synapse's road map.
but now, I remaking synapse's TreeView section.
because I want to reduce the dependent of each functions.

and the file sort has strong relevance with TreeView.

I'll soon reseolved your problem after several times of update

**Comment by magnetas** [comment]
Thanks. Looking forward.

**Comment by magnetas** [comment]
Looks like this is solved. Thank you
